name: GitActions

env:
  MIRROR_URL: "git@github.com:EpitechPromo2027/B-DOP-200-STG-2-1-chocolatine-auguste.mulley.git"
  EXECUTABLES: "antman"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  check_coding_style:
    runs-on: ubuntu-latest
    container: ghcr.io/epitech/coding-style-checker:latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: run
        run: echo HelloWorld
