name: GitActions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  HelloWorld:
    runs-on: ubuntu-latest
    container: ghcr.io/epitech/coding-style-checker:latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: run
        run: echo Hello World
