name: RunUnit

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: install
        run: sudo apt get install -y libcriterion-dev

      - name: compile
        run: gcc -o test pipi.c -lcriterion

      - name: exe
        run: ./test

      - name: Stop Workflow
        if: ${{ failure() }}
        run: exit 1
